oddeye/oddeye/urls.py
from django.contrib import admin
from django.urls import path, include
import styles.views
import accounts.views
import products.views

urlpatterns = [
    path('', styles.views.main, name='main'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('styles/', include('styles.urls')),
    path('products/', include('products.urls')),
    path('aboutus/', accounts.views.aboutus, name='aboutus'),
]

oddeye/products/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.productview, name='products'),
    path('<int:pk>', views.prod_list.as_view(), name='prod_list'),
    path('clientinput',views.ClientInput.as_view(), name='clientinput'),
    path('prod2prod', views.modal_star_and_prod),
]

oddeye/styles/urls.py
from django.contrib import admin
from django.urls import path
from . import views
import products.views

app_name = 'styles'

urlpatterns = [
    path('<cat_no>', views.StylesList, name='list'),
    path('', views.redirectlist, name='styles'),
    path('details/<star_name>/', views.StarView.as_view(), name='detail_styles'),
    path('details/<star_name>/<int:pk>', views.StarView.as_view()),
]

oddeye/templates/base.html
{% load static %}
<!doctype html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="../../static/favicon.png">

    <!-- CSS
	============================================ -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/icons.min.css">
    <link rel="stylesheet" href="/static/css/plugins.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <script src="/static/js/vendor/modernizr-2.8.3.min.js"></script>
    <script src="http://code.jquery.com/jquery-3.1.0.min.js"></script>
</head>


<body>
<header class="header-area clearfix header-hm9 transparent-bar bg-white">
    <div class="container">
        <div class="header-top-area">
            <div class="row">
                <div class="col-lg-5 col-md-8 col-12">
                </div>
                <div class="col-lg-2 d-none d-lg-block">
                    <div class="logo-hm9 text-center">
                        <a href="{% url 'main' %}">
                            <img alt="" src="/static/logo_long.png" width=150px>
                        </a>
                    </div>
                </div>
                <div class="col-lg-5 col-md-4 col-12">
                    <div class="header-right-wrap">


                        <div class="same-style header-search">
                            <a href="/products/clientinput"><i class="pe-7s-camera"></i></a>
                        </div>
                        <div class="same-style account-satting">
                            <a class="account-satting-active" href="#"><i class="pe-7s-user-female"></i></a>
                            <div class="account-dropdown">
                                <ul>
                                    {% if user.is_authenticated %}
                                    <li><a href="{% url 'myaccounts' %}">마이 페이지</a></li>
                                    <li><a href="{% url 'logout' %}">로그아웃</a></li>
                                    {% else %}
                                    <li><a href='{% url "login"%}'>로그인</a></li>
                                    <li><a href="{% url 'register' %}">회원가입</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-bottom sticky-bar header-res-padding header-padding-2">
        <div class="container">
            <div class="row">
                <div class="col-12 d-block d-lg-none">
                    <div class="logo">
                        <a href='{% url "main" %}'>
                            <img alt="" src="/static/logo_long.png" width=150>

                        </a>
                    </div>
                </div>

                <div class="col-xl-12 col-lg-12 d-none d-lg-block">
                    <div class="main-menu div_center">
                        <nav>
                            <ul>
                                <li><a href="{% url 'main' %}">HOME</a></li>
                                <li><a href="{% url 'styles:styles' %}">인물정보</a></li>
                                <li><a href="{% url 'products:products' %}">상품정보</a></li>
                                <li><a href="{% url 'aboutus' %}">About us</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="mobile-menu-area">
                <div class="mobile-menu">
                    <nav id="mobile-menu-active">
                        <ul class="menu-overflow">
                            <li><a href="{% url 'main' %}">HOME</a></li>
                            <li><a href="{% url 'styles:styles' %}">인물정보</a></li>
                            <li><a href="{% url 'products:products' %}">상품정보</a></li>
                            <li><a href="{% url 'aboutus' %}">About us</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>

</header>


<div class="container" style="height:165px"></div>

{% block content %}
{% endblock %}


<footer class="footer-area bg-gray pt-100 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-4 col-sm-4">
                <div class="copyright mb-30">
                    <div class="footer-logo">
                        <a href="{% url 'main' %}">
                            <img alt="" src="/static/logo_final.png" width="100">
                        </a>
                    </div>
                    <p>© 2020 <a href="#">Odd Eye</a>.<br> All Rights Reserved</p>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4">
                <div class="footer-widget mb-30 ml-30">
                    <div class="footer-title">
                        <h3>ABOUT US</h3>
                    </div>
                    <div class="footer-list">
                        <ul>
                            <li><a href="{% url 'aboutus' %}">About us</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-4 col-sm-4">
                <div class="footer-widget mb-30 ml-50">
                    <div class="footer-title">
                        <h3>USEFUL LINKS</h3>
                    </div>
                    <div class="footer-list">
                        <ul>
                            <li><a href="#">Returns</a></li>
                            <li><a href="#">Support Policy</a></li>
                            <li><a href="#">Size guide</a></li>
                            <li><a href="#">FAQs</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="footer-widget mb-30 ml-75">
                    <div class="footer-title">
                        <h3>FOLLOW US</h3>
                    </div>
                    <div class="footer-list">
                        <ul>
                            <li><a href="#">Facebook</a></li>
                            <li><a href="#">Twitter</a></li>
                            <li><a href="#">Instagram</a></li>
                            <li><a href="#">Youtube</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="footer-widget mb-30 ml-70">
                    <div class="footer-title">
                        <h3>SUBSCRIBE</h3>
                    </div>
                    <div class="subscribe-style">
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <div id="mc_embed_signup" class="subscribe-form">
                            <form id="mc-embedded-subscribe-form" class="validate" novalidate="" target="_blank" name="mc-embedded-subscribe-form" method="post" action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef">
                                <div id="mc_embed_signup_scroll" class="mc-form">
                                    <input class="email" type="email" required="" placeholder="Enter your email here.." name="EMAIL" value="">
                                    <div class="mc-news" aria-hidden="true">
                                        <input type="text" value="" tabindex="-1" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef">
                                    </div>
                                    <div class="clear">
                                        <input id="mc-embedded-subscribe" class="button" type="submit" name="subscribe" value="Subscribe">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="/static/js/vendor/jquery-v3.4.1.min.js"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/plugins.js"></script>
<script src="/static/js/ajax-mail.js"></script>
<script src="/static/js/main.js"></script>
{% block jsfooter %}
{% endblock jsfooter %}

<a id="scrollUp" href="#top" style="position: fixed; z-index: 2147483647;"><i class="fa fa-angle-double-up"></i></a>

</body>
</html>