oddeye/oddeye/urls.py
from django.contrib import admin
from django.urls import path, include
import styles.views
import accounts.views
import products.views

urlpatterns = [
    path('', styles.views.main, name='main'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('styles/', include('styles.urls')),
    path('products/', include('products.urls')),
    path('aboutus/', accounts.views.aboutus, name='aboutus'),
]

oddeye/styles/urls.py
from django.contrib import admin
from django.urls import path
from . import views
import products.views

app_name = 'styles'

urlpatterns = [
    path('<cat_no>', views.StylesList, name='list'),
    path('', views.redirectlist, name='styles'),
    path('details/<star_name>/', views.StarView.as_view(), name='detail_styles'),
    path('details/<star_name>/<int:pk>', views.StarView.as_view()),
]

oddeye/styles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Star(models.Model):
    no = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=30)
    likey = models.IntegerField()
    tag = models.CharField(max_length=30)
    style = models.IntegerField()
    category = models.CharField(max_length=100, blank=True, null=True)
#    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='likes')
    # @property
    # def like_count(self):
    #     return self.likes.count()


    
    # likes = models.ManyToManyField(settings.AUTH_USER_MODEL,
    #                                        blank=True,
    #                                        related_name='like_style')

    def __str__(self):
        return self.name+'_'+str(self.style)

    class Meta:
        db_table = 'star'
        verbose_name = '스타'
        verbose_name_plural = '스타'


class Star_embedding3(models.Model):
    no = models.ForeignKey(Star, on_delete=models.CASCADE)
    star_embedding = models.CharField(max_length=2000)

    def __str__(self):
        return self.star_embedding

    class Meta:
        db_table = 'star_embedding3'
        verbose_name = '스타 임베딩3'
        verbose_name_plural = '스타 임베딩3'

class Star_embedding(models.Model):
    no = models.IntegerField()
    star_embedding = models.CharField(max_length=2000)

    def __str__(self):
        return self.star_embedding

    class Meta:
        db_table = 'star_embedding'
        verbose_name = '스타 임베딩1'
        verbose_name_plural = '스타 임베딩1'

class Star_embedding2(models.Model):
    no = models.IntegerField()
    star_embedding = models.CharField(max_length=2000)

    def __str__(self):
        return self.star_embedding

    class Meta:
        db_table = 'star_embedding2'
        verbose_name = '스타 임베딩2'
        verbose_name_plural = '스타 임베딩2'

oddeye/styles/views.py
# django 기능 import
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse,JsonResponse
from django.views.generic import View
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Sum
from styles.models import Star
from accounts.models import OddeyeUsers

# DB import
import cx_Oracle

# 필요한 모듈 import
import os
import random
import numpy as np

# DB data 가져오기
def dictfetchall(cursor):
    desc = cursor.description
    return [dict(zip([col[0] for col in desc], row)) for row in cursor.fetchall()]

# Main Page
def main(req):
    if req.method =="GET":
        style_dir='static/img/removed_bg/'
        stars=os.listdir(style_dir)
        imgs=[]
        for j in range(1, 4):
            for i in stars:
                imgs.append({'name':i, 'img':f"{style_dir}{i}/{str(j)}.png", 'thumb':f"static/star/{i}/thumb/{str(j)}.jpg"})
        random.shuffle(imgs)

        # 스타 추천
        star_name = "irene"
        pk = "4"
        sql = "SELECT style, likey, tag FROM Star WHERE name = '{}' ORDER BY likey desc".format(star_name)
        conn = cx_Oracle.connect('oddeye/1234@15.164.247.135:1522/MODB')
        cursor = conn.cursor()
        cursor.execute(sql)
        db_data_star = dictfetchall(cursor)

        sql = '''
                        SELECT PRODUCTS_EMBEDDING.id, PRODUCTS_EMBEDDING.product_embedding, PRODUCTS.img_url, PRODUCTS.product_url, PRODUCTS.SUPER_CATEGORY, PRODUCTS.BASE_CATEGORY, PRODUCTS.product_name ,PRODUCTS.price_original,PRODUCTS.price_discount
                        FROM PRODUCTS_EMBEDDING
                        JOIN PRODUCTS ON PRODUCTS_EMBEDDING.ID = PRODUCTS.PRODUCT_ID
                        '''
        cursor.execute(sql)
        prod_data = dictfetchall(cursor)

        sql = '''
                SELECT STAR_EMBEDDING.STAR_EMBEDDING, STAR.NAME, STAR.STYLE, STAR.CATEGORY
                FROM STAR_EMBEDDING
                JOIN STAR ON STAR.NO=STAR_EMBEDDING.ID
    
                '''
        cursor.execute(sql)
        star_data = dictfetchall(cursor)
        for s in star_data:
            if s['NAME'] == star_name and int(s['STYLE']) == int(pk):
                star_dict = s
        star_cat = list(map(int, star_dict['CATEGORY'][1:-1].split(',')))

        dist = []
        for i in prod_data:
            if i['PRICE_DISCOUNT']:
                i['discounts'] = int((i['PRICE_ORIGINAL'] - i["PRICE_DISCOUNT"]) / i['PRICE_ORIGINAL'] * 100)
                i['PRICE_DISCOUNT'] = format(i['PRICE_DISCOUNT'], ",")

            if int(i['BASE_CATEGORY']) in star_cat:
                if i["PRICE_DISCOUNT"]:
                    dist.append(
                        {
                            'PRODUCT_NAME': i['PRODUCT_NAME'],
                            'PRODUCT_ID': i['ID'],
                            'distance': compute_linalg_dist(
                                np.array(list(map(float, (star_dict['STAR_EMBEDDING'][2:-2].split(','))))),
                                np.array(list(map(float, (i['PRODUCT_EMBEDDING'][2:-2].split(',')))))),
                            'IMG_URL': i['IMG_URL'],
                            'PRODUCT_URL': i['PRODUCT_URL'],
                            'PRICE_DISCOUNT': i['PRICE_DISCOUNT'],
                            'PRICE_ORIGINAL': format(i['PRICE_ORIGINAL'], ","),
                            'discounts': i['discounts']

                        }
                    )
                else:
                    dist.append(
                        {
                            'PRODUCT_NAME': i['PRODUCT_NAME'],
                            'PRODUCT_ID': i['ID'],
                            'distance': compute_linalg_dist(
                                np.array(list(map(float, (star_dict['STAR_EMBEDDING'][2:-2].split(','))))),
                                np.array(list(map(float, (i['PRODUCT_EMBEDDING'][2:-2].split(',')))))),
                            'IMG_URL': i['IMG_URL'],
                            'PRODUCT_URL': i['PRODUCT_URL'],
                            'PRICE_DISCOUNT': i['PRICE_DISCOUNT'],
                            'PRICE_ORIGINAL': format(i['PRICE_ORIGINAL'], ","),

                        }
                    )

        dist = sorted(dist, key=lambda x: (x['distance'], x['PRODUCT_ID']))

        style_num = pk
        mystyle = Star.objects.all().filter(name=star_name).filter(style=style_num).first()
        cnt = int(mystyle.likey)

        fo = star_name + '_' + str(style_num)
        # 상품 리스트
        sql = '''
                SELECT super_category, base_category, sub_category, product_ID,img_url, product_url,product_name ,price_original,price_discount
                FROM PRODUCTS WHERE rownum <= 8
                '''
        conn = cx_Oracle.connect('oddeye/1234@15.164.247.135:1522/MODB')
        cursor = conn.cursor()
        cursor.execute(sql)
        db_data = dictfetchall(cursor)

        for item in db_data:
            if item['PRICE_DISCOUNT']:
                item['discounts'] = int(
                    (item['PRICE_ORIGINAL'] - item["PRICE_DISCOUNT"]) / item['PRICE_ORIGINAL'] * 100)
                item['PRICE_DISCOUNT_COMMA'] = format(item['PRICE_DISCOUNT'], ",")
            item['PRICE_ORIGINAL_COMMA'] = format(item['PRICE_ORIGINAL'], ",")
        random.shuffle(db_data)
        if req.user.is_authenticated == True:
            current_user = req.session['username']
            myuser = OddeyeUsers.objects.get(username=current_user)
            myfo = myuser.following

            myfo_set = set(myfo.split(','))
            if fo in myfo_set:
                cklike = True
            else:
                cklike = False



            context = {
                "data": imgs,
                'datas': db_data,
                "star_name": star_name,
                'styles': db_data_star,
                "cnt": cnt,
                "cklike": cklike,
                "dist": dist[:6],
                'pk': pk,
                'style_no': pk
            }
        else:
            context={
                "data":imgs,
                "star_name":star_name,
                "styles":db_data_star,
                "pk":pk,
                "style_no":pk,
                "dist":dist[:6],
                "datas":db_data,
                "cnt":cnt
            }
        return render(req, 'styles/main.html', context)

    if req.method == "POST":
        star_name = "irene"
        styles = Star.objects.all()
        style_num = request.POST.get('pk', None)
        mystyle = styles.filter(name=star_name).filter(style=style_num).first()

        cnt = int(mystyle.likey)
        fo = mystyle.name + '_' + str(mystyle.style)
        if req.user.is_authenticated == True:
            current_user = request.session['username']
            myuser = OddeyeUsers.objects.get(username=current_user)
            myfo = myuser.following
            myfo_set = set(myfo.split(','))
            if fo in myfo_set:
                cnt -= 1
                myfo_set.discard(fo)
                print('delete {}'.format(fo))
            else:
                cnt += 1
                myfo_set.add(fo)
                print('add {}'.format(fo))
            mystyle.likey = cnt
            mystyle.save()

            myfo_set.discard('')  # 빈칸을 element로 갖는 경우가 있어서.
            myfo_set_str = str(myfo_set)
            if len(myfo_set) == 0: myfo_set_str = ''  # 빈칸을 set()으로 문자 그대로 넣어서.
            myuser.following = myfo_set_str.replace('{', "").replace('}', "").replace("'", "").replace('"', "").replace(" ",',')
            myuser.save()
            context = {'likes_count': cnt}
        else:
            context={}
        return JsonResponse(context)


def StylesList(req, cat_no, KEYWORD=None):
    KEYWORD = req.GET.get('KEYWORD', None)
    if KEYWORD == None:
        sql = '''
        SELECT NAME, STYLE, LIKEY
        FROM
        (
        SELECT NAME, STYLE, LIKEY, ROW_NUMBER() OVER(PARTITION BY NAME ORDER BY LIKEY DESC) as rn
        FROM STAR
        )
        WHERE rn <= 1
        '''

    else:
        sql = '''
        SELECT NAME, STYLE, LIKEY
        FROM
        (
        SELECT NAME, STYLE, LIKEY, ROW_NUMBER() OVER(PARTITION BY NAME ORDER BY LIKEY DESC) as rn
        FROM STAR
        )
        WHERE rn <= 1 AND NAME = '{}'
        '''.format(KEYWORD.lower())

    conn = cx_Oracle.connect('oddeye/1234@15.164.247.135:1522/MODB')
    cursor = conn.cursor()
    cursor.execute(sql)
    db_data = dictfetchall(cursor)

    if len(db_data)==0:
        return HttpResponse(
            '''
        검색 결과가 없으니 <a href="/styles/">돌아가</a>
        '''
        )
    SQL = '''
        SELECT TAG
        FROM STAR
    '''
    cursor.execute(SQL)
    result = cursor.fetchall()
    tags = []
    for r in result:
        tags.append(r[0])
    tags = sorted(list(set(tags)))
    tag_dict=[]
    for t in range(len(tags)):
        tag_dict.append({'tag_name':tags[t],"tag_no":t+1})
    tag_dict=sorted(tag_dict, key=lambda x: (x['tag_no'], x['tag_name']))
    global tagged_star
    if int(cat_no)==0:
        new_data=db_data

    else:
        filtered_star = []
        for star in tagged_star:
            if int(cat_no) in star['tag']:
                filtered_star.append(star['name'])
        new_data=[]
        for data in db_data:
            if data['NAME'] in filtered_star:
                new_data.append(data)

    page = req.GET.get('page',1)
    p = Paginator(new_data, 6)
    sub = p.page(page)

    context = {'stars':sub, 'tags':tag_dict, "page":page, 'KEYWORD':KEYWORD}
    return render(req, 'styles/list.html', context)

def redirectlist(req):
    return redirect('styles:list','0')

class StarView(View):
    def get(self, req, star_name,pk=1):
        star_name=star_name
        sql = "SELECT style, likey, tag FROM Star WHERE name = '{}' ORDER BY likey desc".format(star_name)

oddeye/templates/styles/detail.html
<style>
    .owl-carousel {
        position: relative;
        width: 440 !important;
        height: 440;
        margin: 50 0 100 0 ;
    }
    
    @media only screen and (min-width: 768px) {
        .owl-stage {
            transform: none !important;
            width: 440 !important;
        }

        .owl-carousel .owl-stage-outer {
            width: 110%;
            overflow: visible !important;
        }

        .owl-carousel .owl-item img {
            width: 200 !important;
            display: inline-grid;
            float: none;
        }
    }
</style>

{% extends "base.html" %}

{% block title %}
style-detail
{% endblock title %}

{% load static %}

{% block content %}
<div class="container">
    <div class="shop-area pb-50 row">
        <!-- 선택된 이미지 크게 -->
        <div class="selected col-sm-4 col-lg-4 sidebar-active sidebar-active-left">
            <div class="row">
                <div class="col">
                    <div id="selected_thumbnail" class="product-details">
                        <img width="300px" id="star_thumb" class="circular--square star_large" src='{% static "" %}star/{{star_name}}/thumb/{{pk}}.jpg'>
                    </div>
                </div>
                <div class="col"></div>
            </div>
            <div class="row">
                <div class="col pt-30">
                    <div class="product-details-content" style="width: 100%;text-align: center;">
                        <h2>{{star_name|upper}}</h2>
                        <div class="icon_heart">
                            <a href="#" id="1" name="17" class="icons likey"  data-toggle="tooltip" data-placement="bottom" title="Follow">
                                {% if cklike == True %}
                                <i class="fa fa-heart fa-lg"></i>
                                {% else %}
                                <i class="fa fa-heart-o icon-default fa-lg"></i>
                                <i class="fa fa-heart icon-hover fa-lg"></i>
                                {% endif %}
                            </a>
                        </div>
                        <div class="inline_block_count">{{ total_cnt }}</div><br>
                        <div class="pro-details-meta inline_block_tag">
                            <span class="inline_block">TAGS :</span>
                            <ul class="inline_block">
                                <li><a href="#"> {{styles.0.TAG}} </a></li>
                                <li><a href="#"> {{styles.1.TAG}} </a></li>
                                <li><a href="#"> {{styles.2.TAG}} </a></li>
                                <li><a href="#"> {{styles.3.TAG}} </a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-30 mb-30">
                <div class="col-lg-3 col-xs-6">
                    <a href="/styles/details/{{star_name}}/{{styles.0.STYLE}}">
                        <img id="01" name="{{ styles.NO }}" class="circular--square star_small" src='{% static "" %}star/{{star_name}}/thumb/{{styles.0.STYLE}}.jpg'></a>
                </div>
                <div class="col-lg-3 col-xs-6">
                    <a href="/styles/details/{{star_name}}/{{styles.1.STYLE}}">
                        <img id="02" name="{{ styles.NO }}" class="circular--square star_small" src='{% static "" %}star/{{star_name}}/thumb/{{styles.1.STYLE}}.jpg'></a>
                </div>
                <div class="col-lg-3 col-xs-6">
                    <a href="/styles/details/{{star_name}}/{{styles.2.STYLE}}">
                        <img id="03" name="{{ styles.NO }}" class="circular--square star_small" src='{% static "" %}star/{{star_name}}/thumb/{{styles.2.STYLE}}.jpg'></a>
                </div>
                <div class="col-lg-3 col-xs-6">
                    <a href="/styles/details/{{star_name}}/{{styles.3.STYLE}}">
                        <img id="04" name="{{ styles.NO }}" class="circular--square star_small" src='{% static "" %}star/{{star_name}}/thumb/{{styles.3.STYLE}}.jpg'></a>
                </div>
            </div>
        </div>


        <div class="col"></div>
        <div class="col-lg-7 pt-50">
            <!--SECTION2: Related Products -->
            <div class="related-product-area pb-95">
                <div class="section-title text-center mb-20">
                    <h2>Related products</h2> <br>
                    <!--                    <h2 class='jquery_test'> {{style_no}}</h2>-->
                </div>
                <div class="product-area hm5-section-padding pt-20 pb-20">
                    <div class="row">
                        {% for d in dist %}
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12">
                            <div class="product-wrap-3 mb-20 scroll-zoom">
                                <div class="product-img">
                                    <a href="#" data-toggle="modal" data-target="#exampleModal{{d.product_id}}" ><img src={{d.img_url}} alt=""></a>
                                    {% if d.discounts %}
                                    <span class="pink">-{{d.discounts}}%</span>
                                    {% endif %}
                                    <div class="product-content-3-wrap">
                                        <div class="product-content-3">
                                            <div class="product-title">
                                                <h3><a href="{{d.product_name}}" data-toggle="modal" data-target="#exampleModal{{d.product_id}}">{{d.product_name}}</a></h3>
                                            </div>
                                            {% if d.price_discount != None%}
                                            <div class="price-3">
                                                <span>₩ {{d.price_discount}}</span>
                                                <span class="old">₩{{d.price_original}}</span>
                                            </div>

                                            {% else %}
                                            <div class="price-3">
                                                <span>₩ {{d.price_original}}</span>
                                            </div>
                                            {% endif %}
                                            <div class="product-action-3 wishlist" name="{{d.product_id}}">
                                                <a title="Add To Wishlist" href="#"><i class="fa fa-heart"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal start-->
{% for d in dist %}
<div class="modal fade" id="exampleModal{{d.product_id}}" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <span>상품 상세보기</span>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">x</span></button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 col-xs-12">
                            <div class="tab-content quickview-big-img">
                                <div id="pro-2" class="tab-pane fade show active">
                                    <img src="{{ d.img_url }}" alt="">
                                </div>
                            </div>
                            <!-- Thumbnail Large Image End -->
                            <!-- Thumbnail Image End -->
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12">
                            <div class="product-details-content quickview-content">
                                <h2>{{d.product_name}}</h2>
                                <div class="product-details-price">
                                    {% if d.price_discount != None%}
                                    <span>₩ {{d.price_discount}}</span>
                                    <span class="old">₩{{d.price_original}}</span>
                                    {% else %}
                                    <span>₩ {{d.price_original}}</span>
                                    {% endif %}
                                </div>
                                <div class="pro-details-quality">
                                    <div class="pro-details-cart btn-hover">
                                        <a href="{{d.product_url}}">구매하러가기</a>
                                    </div>
<!--                                    <div class="pro-details-wishlist">-->
<!--                                        <a href="#"><i class="fa fa-heart-o"></i></a>-->
<!--                                    </div>-->
                                </div>
                                <div class="pro-details-meta">
                                    <span>Tag :</span>
                                    <ul>
                                        <li><a href="#"># Fashion </a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<!-- Modal end -->



{% endblock %}

{% block jsfooter %}

<script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
<script>
    $(document).ready(function(){
        //캐로셀
        $('#style_carousel').owlCarousel({
            loop: true,
            nav: true,
            autoplay: false,
            autoplayTimeout: 5000,
            animateOut: 'fadeOut',
            animateIn: 'fadeIn',
            navText: ['<i class="fa fa-chevron-left"></i>', '<i class="fa fa-chevron-right"></i>'],
            item: 4,
            margin: 30,
            responsive: {
                0: {
                    items: 1
                },
                768: {
                    items: 2
                },
                1000: {
                    items: 4
                }
            }
        });
        //현재 style num 가져오기


        //style 마우스 오버 시 썸네일 바뀜 + 마우스 리브 시 썸네일 돌아옴 <-- 마우스리브 아직 못 함
        // $('.other_styles a img').mouseover(function(){
        //     var go = $(this).attr('src');
        //     $('#star_thumb').attr('src', go);
        // });
    
        //style 클릭 시 썸네일 바뀌는 효과
        $('.other_styles a img').click(function(){
            var go = $(this).attr('src')
            $('#star_thumb').fadeOut(100, function(){
                $('#star_thumb').attr('src', go).fadeIn(200);
                return false;
            });

            // var myurl = '/details/' + {{star.NAME}} + {{star.STYLE}};
            // $(location).attr('href',myurl);
        });
    
        $('.other_styles a img').click(function(){
            var star_id = $(this).attr('id');
            var param = {star_id:star_id};
            $(".jquery_test").text(star_id);
        });

        $('.likey').click(function(){
            // var pk = $(this).attr('name');
            var pk={{pk}}
            var style_num = $(this).attr('id');
            var star_name = '{{star_name}}';

            $.ajax({
                type: "POST",
                url: "{% url 'styles:detail_styles' star_name  %}",
                data: {'pk': pk, 'star_name':star_name, 'style':style_num, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: "json",

                success: function (response) {
                    // id = $(this).attr('name');
                    // $('#count'+ pk).html("count : "+ response.likes_count);
                    // alert("좋아요수 :" + response.likes_count);
                    // alert(response.message);
                    location.reload();
                },
                error: function (request, status, error) {
                    console.log("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error + "\n")
                }
            });
        })
    });

</script>
{% endblock jsfooter %}